name: Linting

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Cancel Outdated Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip3-${{ hashFiles('*requirements.txt') }}
      - run: pip install wheel
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Run Flake8
        run: flake8
      - name: Black code style
        run: black . --check --target-version py310 --exclude '\.mypy_cache/|\.venv/|env/|(.*/)*snapshots/|.pytype/'
      - name: Docstring formatting
        run: docformatter -c -r . --wrap-summaries 88 --wrap-descriptions 88
      - name: Check import order with isort
        run: isort . --check --diff
      - name: PyType type-check
        run: pytype -j auto .
